# Generated by Django 2.2.4 on 2019-09-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190906_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_merchant',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='postal_code_4',
        ),
        migrations.AddField(
            model_name='profile',
            name='address_2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='locatity',
            field=models.CharField(max_length=30),
        ),
    ]
