# Generated by Django 2.2.4 on 2019-09-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190910_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undefined')], default=3, max_length=1, verbose_name='GENDER'),
        ),
    ]
