# Generated by Django 2.2.4 on 2019-09-10 00:57

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='static/images/user-default.jpg', upload_to=users.models.upload_to, verbose_name='Profile Photo'),
        ),
    ]
