# Generated by Django 2.2.4 on 2019-09-04 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190904_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='writing',
            new_name='article',
        ),
    ]
