# Generated by Django 2.2.4 on 2019-09-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20190904_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.IntegerField(default=0),
        ),
    ]
