# Generated by Django 2.2.4 on 2019-09-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20190909_0147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-releaseDate'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
